apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: orders-connector
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    connector.class: "io.debezium.connector.sqlserver.SqlServerConnector"
    database.hostname: "mssql-server-linux.shared-db-earth.svc"
    database.port: "1433"
    database.user: "sa"
    database.password: "Password!"
    database.dbname: "InternationalDB"
    database.server.name: "user1.earth"
    table.whitelist: "dbo.Orders"
    database.history.kafka.bootstrap.servers: "earth-cluster-kafka-bootstrap.integration-demo.svc:9092"
    database.history.kafka.topic: "user1.earth.dbhistory"